### PR TITLE
Added progress bar on taskbar

### PR DESCRIPTION
**Pull request by 1nikolas**
I added another feature, code is simple but useful (that's all I can do 🙁). Again it should work, never tested. Also it needs 2 dlls to import you can get them [here](https://puu.sh/BsK45/1a56b770d8.zip)
[I got the dlls from NuGet, see [here](https://www.nuget.org/packages/WindowsAPICodePack-Shell) and [here](https://www.nuget.org/packages/WindowsAPICodePack-Core/)]

**Note: check failed because its missing the dlls**

### CODE REVIEW

**Comment by JonasNilson** [comment]
Thanks for the suggestion. I might have time to test it out during the weekend, but I can't make any promises at this time.

**Comment by 1nikolas** [comment]
Okay no problem

**Comment by gerka13** [comment]
somebody can add option 

> Thanks for the suggestion. I might have time to test it out during the weekend, but I can't make any promises at this time.

can you add option "reduce "next check" time for fast mode from 15 min to 10 sec"" (at last page)
explain : this option need when you very fast farm many cards (15000 for ex) from one game in short time.ty.

**Comment by 1nikolas** [comment]
@gerka13 you could use fast mode from settings. With this it tells steam that you play all these games so the refresh rate doesen't matter

**Comment by gerka13** [comment]
> @gerka13 you could use fast mode from settings. With this it tells steam that you play all these games at the same time so the refresh rate doesen't matter

method i post earlier lets drop 1 card in 15-20 sec( if you have only 1 game with cards, more games- hight drop rate). you very wrong, 
how drop rate if use standard fast mode? =)

**Pull request closed without merging**
